# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atarashi/paddle/data/example.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (
    lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from atarashi.paddle.data import feature_pb2 as atarashi_dot_paddle_dot_data_dot_feature__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='atarashi/paddle/data/example.proto',
    package='atarashi',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\"atarashi/paddle/data/example.proto\x12\x08\x61tarashi\x1a\"atarashi/paddle/data/feature.proto\"/\n\x07\x45xample\x12$\n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\x12.atarashi.Features\"e\n\x0fSequenceExample\x12#\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x12.atarashi.Features\x12-\n\rfeature_lists\x18\x02 \x01(\x0b\x32\x16.atarashi.FeatureListsb\x06proto3'
    ),
    dependencies=[atarashi_dot_paddle_dot_data_dot_feature__pb2.DESCRIPTOR, ])

_EXAMPLE = _descriptor.Descriptor(
    name='Example',
    full_name='atarashi.Example',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='features',
            full_name='atarashi.Example.features',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=84,
    serialized_end=131, )

_SEQUENCEEXAMPLE = _descriptor.Descriptor(
    name='SequenceExample',
    full_name='atarashi.SequenceExample',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='context',
            full_name='atarashi.SequenceExample.context',
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='feature_lists',
            full_name='atarashi.SequenceExample.feature_lists',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=133,
    serialized_end=234, )

_EXAMPLE.fields_by_name[
    'features'].message_type = atarashi_dot_paddle_dot_data_dot_feature__pb2._FEATURES
_SEQUENCEEXAMPLE.fields_by_name[
    'context'].message_type = atarashi_dot_paddle_dot_data_dot_feature__pb2._FEATURES
_SEQUENCEEXAMPLE.fields_by_name[
    'feature_lists'].message_type = atarashi_dot_paddle_dot_data_dot_feature__pb2._FEATURELISTS
DESCRIPTOR.message_types_by_name['Example'] = _EXAMPLE
DESCRIPTOR.message_types_by_name['SequenceExample'] = _SEQUENCEEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Example = _reflection.GeneratedProtocolMessageType(
    'Example',
    (_message.Message, ),
    dict(
        DESCRIPTOR=_EXAMPLE,
        __module__='atarashi.paddle.data.example_pb2'
        # @@protoc_insertion_point(class_scope:atarashi.Example)
    ))
_sym_db.RegisterMessage(Example)

SequenceExample = _reflection.GeneratedProtocolMessageType(
    'SequenceExample',
    (_message.Message, ),
    dict(
        DESCRIPTOR=_SEQUENCEEXAMPLE,
        __module__='atarashi.paddle.data.example_pb2'
        # @@protoc_insertion_point(class_scope:atarashi.SequenceExample)
    ))
_sym_db.RegisterMessage(SequenceExample)

# @@protoc_insertion_point(module_scope)
